"""
YSFC Forge — Effect Preset Definitions

Officiell lista över factory presets per effekt-typ.
Källa: Härlett ur Yamahas publicerade MODX M Data List
(© Yamaha Corporation). Endast funktionella fakta extraheras, för interoperabilitet med det odokumenterade
Y2L/Y2U-filformatet. Yamahas dokument återdistribueras inte här —
originalet finns hos Yamaha: https://download.yamaha.com
(sök "MODX M Data List").
"""

# {effect_type_name: [preset_name, preset_name, ...]}
FX_PRESETS = {
'HD Hall': ['Large Hall', 'Medium Hall', 'Bright Hall', 'Warm', 'Small'],
 'REV-X Hall': ['Basic', 'Small Hall', 'Clean', 'Church', 'Bright Hall'],
 'R3 Hall': ['Basic', 'Large Hall', 'Backstage', 'Ballad', 'Light'],
 'SPX Hall': ['Basic', 'Large Hall', 'Backstage', 'Light', 'Gymnasium'],
 'HD Room': ['Small', 'Medium', 'Large', 'Presence', 'Warm', 'Open'],
 'REV-X Room': ['Basic', 'Basement', 'Garage', 'Bedroom'],
 'R3 Room': ['Basic', 'Open', 'Wide', 'Tight'],
 'SPX Room': ['Basic', 'Open', 'Wide', 'Tight'],
 'HD Plate': ['Large Plate', 'Medium Plate', 'Bright Plate', 'Warm Plate', 'Rattle Plate'],
 'R3 Plate': ['Basic', 'Bright Vocal', 'Smooth Vocal', 'Short Bright', 'Metal Splash'],
 'SPX Stage': ['Basic', 'Small', 'Large', 'Warm', 'Presence'],
 'Space Simulator': ['Tunnel',
                     'Basement',
                     'Canyon',
                     'White Room',
                     'Small Room',
                     'Live Room',
                     'Three Walls'],
 'Shimmer Reverb': ['Basic', 'Ambient', 'AM', 'Mod Reverb'],
 'Gated Reverb': ['Gated Reverb 1', 'Gated Reverb 2', 'Gate Delay 1', 'Gate Delay 2'],
 'Reverse Reverb': ['Basic', 'Long', 'Short', 'Rvs Delay 1', 'Rvs Delay 2'],
 'Cross Delay': ['Basic', 'Short', 'Long', 'Very Long'],
 'Tempo Cross Delay': ['1/8 & 1/32D',
                       '1/16 Echo',
                       '1/8T & 1/4T',
                       '1/16T Echo',
                       '1/4 Echo',
                       'Dotted 1/8 Echo',
                       '1/8 Echo',
                       'Triplet Echo',
                       '1/2 Echo'],
 'Tempo Delay Mono': ['1/4T L/R Diff',
                      '1/8T L/R Diff',
                      '1/4 Echo',
                      '1/4 Mono',
                      'Dotted 1/8 Echo',
                      '1/8 Echo',
                      'Dotted 1/8 Mono',
                      '1/8 Mono',
                      'Triplet Echo',
                      'Triplet Mono',
                      'Analog Delay'],
 'Tempo Delay Stereo': ['1/4T L/R Diff',
                        '1/8T L/R Diff',
                        '1/4 Echo',
                        'Dotted 1/8 Echo',
                        '1/8 Echo',
                        'Triplet Echo'],
 'Control Delay': ['Basic', 'Transition Slow', 'Transition Fast'],
 'Delay LR': ['Basic', 'Doubling', 'Short', 'Fast', 'Long', 'Very Long', 'Analog Delay'],
 'Delay LCR': ['Bright', 'Warm', 'Bounce', 'Analog Delay'],
 'Analog Delay Retro': ['Mellow',
                        'Magical Dawn',
                        'Reel to Reel',
                        'Bright Dub',
                        'Magical Dusk',
                        'Deep',
                        'Lo-Fi Echo',
                        'Oil',
                        'Dark Room',
                        'Smokey Dub'],
 'Analog Delay Modern': ['Urban',
                         'Soft Rock',
                         'Reel to Reel',
                         'Dub Long',
                         'Bucket Rev',
                         'Clear Black',
                         'Dub Short',
                         'Lo-Fi Echo',
                         'Dark Room',
                         'New Wave'],
 'G Chorus': ['Basic', 'Fast', 'Deep', 'Mist', 'Bright'],
 '2 Modulator': ['Basic',
                 'Fast',
                 'Deep',
                 'Mist',
                 'Multi',
                 'Panning Mod',
                 'Vibrator',
                 'Wonder',
                 'Shimmer'],
 'SPX Chorus': ['Basic', 'Fast', 'Deep', 'Slow', 'Flangy'],
 'Symphonic': ['Basic', 'Fast', 'Deep', 'Slow', 'Analog'],
 'Ensemble Detune': ['Basic', 'Soft Wide', 'Deep Wide', 'Stereo Sim'],
 'GS1 Ensemble & Tremolo': ['Basic', 'Ens with Trm', 'Mono', 'Chorus'],
 'VCM Flanger': ['Basic', 'Jet', 'Deep Mod 1', 'Deep Mod 2', 'Mad Mod'],
 'Classic Flanger': ['Basic', 'Flange Chorus', 'Psychedelic', 'Jet'],
 'Tempo Flanger': ['Deep Mod', 'Flange Chorus', 'Metallic', 'Psychedelic', 'Jet'],
 'Dynamic Flanger': ['Follow', 'Reverse', 'Distorted', 'Sync'],
 'Control Flanger': ['Comb 1', 'Comb 2', 'Comb 3'],
 'VCM Phaser Mono': ['Stage 4',
                     'Stage 6',
                     'Stage 8',
                     'Stage 10',
                     'Stage 12',
                     'Stage 16',
                     'E.Piano',
                     'Orange 90',
                     'Two Phase',
                     'Deep Six',
                     'Deep Eight',
                     'Lite Eight',
                     'Deep Sweeper',
                     'Orange 100',
                     'Red Twelve',
                     'Blue Sixteen',
                     'Clavi 1',
                     'Clavi 2',
                     'E.Guitar 1',
                     'E.Guitar 2',
                     'E.Guitar 3',
                     'Vibrato 1',
                     'Vibrato 2',
                     'Vibrato 3',
                     'Ambience 1',
                     'Ambience 2'],
 'VCM Phaser Stereo': ['Stage 4',
                       'Stage 6',
                       'Stage 8',
                       'Stage 10',
                       'Deep Sweeper',
                       'E.Piano 1',
                       'E.Piano 2',
                       'Clavi 1',
                       'Clavi 2',
                       'E.Guitar 1',
                       'E.Guitar 2',
                       'E.Guitar 3',
                       'Deep Six',
                       'Deep Eight',
                       'Vibrato 1',
                       'Vibrato 2',
                       'Vibrato 3',
                       'Ambience 1',
                       'Ambience 2'],
 'Tempo Phaser': ['Stage 4', 'Stage 6', 'Stage 8', 'Stage 10', 'Stage 12', 'Stage 18'],
 'Dynamic Phaser': ['Up', 'Down', 'Follow', 'Reverse', 'Light'],
 'Control Phaser': ['Stage 4', 'Stage 6', 'Stage 8', 'Stage 10'],
 'Auto Pan': ['E.Piano', 'Smooth', 'Oval', 'Right Turn', 'Super Slow'],
 'Tremolo': ['Fast', 'Slow', 'Super Fast', 'Stereo Vibrato', 'Spring', 'Relax'],
 'Rotary Speaker 1': ['Basic', 'Horn Mic', 'Light', 'Heavy Rotor', 'Fast First'],
 'Rotary Speaker 2': ['Clean and Wide',
                      'Vintage Mono',
                      'Slow and Dirty',
                      'Full Drive',
                      'Broken Motors'],
 'VCM Rotary Speaker Classic': ['Basic', 'Warm', 'Bright'],
 'VCM Rotary Speaker Overdrive': ['Basic', 'Warm', 'Bright'],
 'VCM Rotary Speaker Studio': ['Basic', 'Warm', 'Bright'],
 'Amp Simulator 1': ['Stack 1',
                     'Stack 2',
                     'Twin Boost',
                     'Old Amp',
                     'Transistor',
                     'Modern',
                     'US-Clean',
                     'J-Clean',
                     'Fuzz',
                     'Small Blues',
                     'Buzzy Bottom',
                     'Beat Crunch',
                     'Beat Drive'],
 'Amp Simulator 2': ['Stack 1',
                     'Stack 2',
                     'Combo',
                     'Crunch',
                     'Hi Gain',
                     'British',
                     'Tube Drive',
                     'Tube Clean'],
 'Comp Distortion': ['Basic', 'Booster', 'School Boy', 'Detroit', 'Long Lead', '80s Clean'],
 'Comp Distortion Delay': ['Hard 1',
                           'Hard 2',
                           'Grunge',
                           'Voodoo',
                           'Texas',
                           'Rockabilly',
                           'LA Session',
                           'Thin Techno'],
 'U.S. Combo': ['Twin', 'Rich Clean', 'Thin Clean', 'Crunch'],
 'Jazz Combo': ['Basic',
                'Warm Chorus',
                'Vibrato',
                'Keyboard Amp',
                'Kbd Amp Dist 1',
                'Kbd Amp Dist 2'],
 'U.S. High Gain': ['Dirty', 'Riff', 'Burn', 'Solo'],
 'British Lead': ['Dirty', 'Drive', 'Gainer', 'Hard'],
 'Multi FX': ['Distortion Solo',
              'Distortion Basic',
              'Overdrive Chorus',
              'Crunch Wah',
              'Oldies Delay',
              'Vintage Echo'],
 'Small Stereo': ['Distortion', 'Overdrive', 'Vintage Amp', 'Heavy Dist'],
 'British Combo': ['Classic', 'Top Boost', 'Custom', 'Heavy'],
 'British Legend': ['Blues', 'Heavy 1', 'Heavy 2', 'Clean', 'Dirty Clean'],
 'VCM Compressor 376': ['Basic',
                        'Comp Sustainer',
                        '60s Drum Kit',
                        'Natural Kick',
                        'Old Piano',
                        'Valve Tone Bass',
                        'Hard Basic',
                        'Fast Atk + Boost',
                        'Soft Atk + Boost',
                        'Attack & Tight',
                        'Hard Atk + Boost',
                        'Vocal Comp 117x',
                        'Unplugged',
                        'Attack Comp',
                        'Punchy Master',
                        'Pinched'],
 'Classic Compressor': ['Basic',
                        'Attack',
                        'For Vintage Keys',
                        'Pack Comp',
                        'Gate',
                        'TightPopRhythm',
                        'Cutting Comp',
                        'Basic Bass',
                        'Old Record Piano'],
 'Multi-band Comp': ['Basic', 'Maximizer', 'Wild', 'Attacky', 'Hard', 'Hip Club', 'Slap Bass (ch)'],
 'Uni Comp Down': ['Basic', 'Warm', 'Bright', 'Sat Comp', 'Comp + Hard Clip', 'Master'],
 'Uni Comp Up': ['Basic', 'Warm', 'Bright', 'Sat Comp', 'Comp + Hard Clip', 'Master'],
 'Parallel Comp': ['Natural',
                   'Rich',
                   'Punchy',
                   'Electronic',
                   'Loud',
                   'Natural for Mst',
                   'Rich for Master',
                   'Punchy for Mst',
                   'ElectronicForMst',
                   'Loud for Master'],
 'M/S EQ Compressor': ['Wide Side',
                       'Mid Punchy',
                       'Natural',
                       'Attack',
                       'Loud',
                       'Comp Sat',
                       'Limit Sat',
                       'Lo-Fi Limiter',
                       'Master Comp'],
 'VCM Auto Wah': ['Clean Mid',
                  'Clean High',
                  'Clean Low',
                  'Clean Bass',
                  'Overdrive Mid',
                  'Overdrive High',
                  'Overdrive Low',
                  'Overdrive Bass'],
 'VCM Touch Wah': ['Clean Mid',
                   'Clean High',
                   'Clean Low',
                   'Clean Bass',
                   'Overdrive Mid',
                   'Overdrive High',
                   'Overdrive Low',
                   'Overdrive Bass',
                   'Follow',
                   'Hi Q',
                   'For Bass',
                   'Reverse'],
 'VCM Pedal Wah': ['Clean Mid',
                   'Clean High',
                   'Clean Low',
                   'Clean Bass',
                   'Overdrive Mid',
                   'Overdrive High',
                   'Overdrive Low',
                   'Overdrive Bass'],
 'Lo-Fi': ['Lo-Fi', 'Old Phone', 'Overload', 'Max Lo-Fi'],
 'Noisy': ['Nz Drive',
           'Soft Nz Tremolo',
           'Nz Rotary 1',
           'Nz Rotary 2',
           'Noisy',
           'Tremolo Noise',
           'Fuzz Noise'],
 'Digital Turntable': ['Digi Nz',
                       '78 rpm',
                       '45 rpm',
                       '331/3 rpm',
                       'Old Record 1',
                       'Old Record 2',
                       'Short Wave Radio'],
 'Bit Crusher': ['Hard',
                 'Soft',
                 '12-bit Sampler',
                 'Mid-Side 1',
                 'Mid-Side 2',
                 'Mid-Side 3',
                 '2-bit Dist'],
 'Ring Modulator': ['Basic', 'Slow', 'Tremolo', 'Crazy'],
 'CS Ring Modulator': ['Up & Down',
                       'Bounce',
                       'Oval Tremolo',
                       'Tremoriser',
                       'Change Tremolo',
                       'Stable',
                       'Rotator',
                       'Under Tone'],
 'Dynamic Ring Modulator': ['Basic', 'Metallic', 'Sputter', 'Sharp Edge'],
 'Dynamic Filter': ['Basic', 'High Pass', 'Low Pass', 'Squish'],
 'Auto Synth': ['Nz Mod Delay 1',
                'Nz Mod Delay 2',
                'Nz Mod Delay 3',
                'Nz Mod Delay 4',
                'Echo',
                'Space Walking',
                'Robot Delay'],
 'Spiralizer P': ['Basic', 'Step 1', 'Scale', 'Step 2', 'Slow'],
 'Tempo Spiralizer P': ['Basic', 'Step 1', 'Scale', 'Step 2', 'Slow'],
 'Spiralizer F': ['Basic', 'Step 1', 'Scale', 'Step 2', 'Slow'],
 'Tempo Spiralizer F': ['Basic', 'Step 1', 'Scale', 'Step 2', 'Slow'],
 'Isolator': ['Lo/Hi Boost', 'Hi Cut', 'Lo Only', 'Mid Only', 'Lo Cut', 'Near', 'Flat'],
 'Slice': ['Basic', 'Slice Beat', '8th Pan', '16th Mute', 'Rock'],
 'Tech Modulation': ['Mod Chase',
                     'Mod Dub',
                     'Star Train',
                     'Numerator',
                     'Active Dist',
                     'Astonish',
                     'Drift Armor'],
 'Control Filter': ['LPF12', 'LPF18', 'LPF24', 'BPF', 'HPF'],
 'Vinyl Break': ['Fast', 'Middle', 'Slow', 'Vinyl Stop', 'Power off'],
 'Beat Repeat (even)': ['1/16 x 4',
                        '1/16 x 4 Rev.',
                        'Trans Gate',
                        'Trans Gate + HPF',
                        'Pitch Sweep',
                        'PitchSweep+HPF',
                        'Slow Attack Echo',
                        'Broken'],
 'Beat Repeat (triplet)': ['Triplet x 4',
                           'Triplet x 4 Rev.',
                           'Trans Gate',
                           'Trans Gate + HPF',
                           'Pitch Sweep',
                           'PitchSweep+HPF',
                           'Slow Attack Echo',
                           'Broken'],
 'Beat Repeat (evn+tri.)': ['1/16 x 4',
                            '1/16 x 4 Rev.',
                            'Trans Gate',
                            'Trans Gate + HPF',
                            'Pitch Sweep',
                            'PitchSweep+HPF',
                            'Slow Attack Echo',
                            'Broken'],
 'Beat Repeat (free)': ['1/16 x 4',
                        '1/16 x 4 Rev.',
                        'Trans Gate',
                        'Trans Gate + HPF',
                        'Pitch Sweep',
                        'PitchSweep+HPF',
                        'Slow Atk Echo',
                        'Broken',
                        'Quintuplet'],
 'VCM EQ 501': ['Basic',
                'Bright',
                'Warm',
                'Lo/Hi Boost',
                'Mid Boost',
                'Loud',
                'Dance SD/BD',
                'Radio Speaker',
                'Flat'],
 'Presence': ['Natural', 'Heavy', 'Bright'],
 'Harmonic Enhancer': ['Presence', 'Edge', 'High Edge', 'Mid Edge'],
 'Stereophonic Optimizer': ['Focus',
                            'Bottom',
                            'Top',
                            'Center',
                            'Acoustic Piano',
                            'Drum',
                            'EP Tremolo',
                            'Organ',
                            'Sax'],
 'Talking Modulator': ['Basic', 'Slow'],
 'Wave Folder': ['Soft 1',
                 'Soft 2',
                 'Hard 1',
                 'Hard 2',
                 'SEQ+LFO 01',
                 'SEQ+LFO 02',
                 'SEQ+LFO 03',
                 'SEQ+LFO 04',
                 'SEQ+LFO 05',
                 'SEQ+LFO 06',
                 'SEQ+LFO 07',
                 'SEQ+LFO 08',
                 'SEQ+LFO 09',
                 'SEQ+LFO 10',
                 'Saturator 1',
                 'Saturator 2',
                 'Saturator 3',
                 'Saturator 4'],
 'VCM Mini Filter': ['1970s LPF',
                     '1980s LPF',
                     'Modern LPF',
                     '1970s HPF',
                     '1980s HPF',
                     'Modern HPF'],
 'VCM Mini Booster': ['1970s High Boost',
                      '1980s High Boost',
                      'ModernHighBoost',
                      '1970s Low Boost',
                      '1980s Low Boost',
                      'Modern LowBoost'],
 'Damper Resonance': ['Basic', 'String Reso', 'Short', 'Long'],
 'Pitch Change': ['Detune',
                  'Oct Echo',
                  'Octaver',
                  'Plus 4th',
                  'Minus 4th',
                  'Oval',
                  'Step Up',
                  'Step Down'],
 'Early Reflection': ['Close', 'Far', 'Reverse', 'Gate', '70s Gate'],
 'Vocoder': ['Basic', 'Fast', 'Slow'],
 'NoiseGate + Comp + Eq': ['Basic', 'Soft Comp', 'Hard Comp', 'Limiter']}


def get_presets(fx_name):
    """Returns list of presets for an effect (or empty list)."""
    return FX_PRESETS.get(fx_name, [])


if __name__ == '__main__':
    total = sum(len(p) for p in FX_PRESETS.values())
    print(f"Total effects with presets: {len(FX_PRESETS)}")
    print(f"Total preset entries: {total}")
