"""
YSFC Forge — Effect Type Definitions

Officiell lista över alla 103 effekter i Yamaha MODX M / Montage M.
Källa: Effect Type List (Yamaha officiell dokumentation)

Varje effekt har:
- name: officiellt namn
- short_name: kort namn (REV/DLY/CHO/FLG/PHA/etc.)
- category: REVERB/DELAY/CHORUS/etc.
- msb, lsb: byte-värden för identifiering
- per-slot index: vilken position effekten har i vald slot
  (rev, var, insa, insb, adins, vcm, mas)
  None = ej tillgänglig i den slotten
"""

# {effect_name: {field: value}}
FX_TYPES = {
    'NO EFFECT': {
        'category': None,
        'short_name': '---',
        'msb': 0,
        'lsb': 0,
        'rev': 0,
        'var': 0,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': None,
        'mas': None,
    },
    'THRU': {
        'category': None,
        'short_name': '---',
        'msb': 0,
        'lsb': 0,
        'rev': None,
        'var': None,
        'insa': 0,
        'insb': 0,
        'adins': 0,
        'vcm': None,
        'mas': None,
    },
    'HD HALL': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 3,
        'rev': 1,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': None,
        'mas': None,
    },
    'REV-X HALL': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 0,
        'rev': 2,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': None,
        'mas': None,
    },
    'R3 HALL': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 1,
        'rev': 3,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': None,
        'mas': None,
    },
    'SPX HALL': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 2,
        'rev': 4,
        'var': 1,
        'insa': 1,
        'insb': 1,
        'adins': 1,
        'vcm': None,
        'mas': None,
    },
    'HD ROOM': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 13,
        'rev': 5,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': None,
        'mas': None,
    },
    'REV-X ROOM': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 10,
        'rev': 6,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': None,
        'mas': None,
    },
    'R3 ROOM': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 11,
        'rev': 7,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': None,
        'mas': None,
    },
    'SPX ROOM': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 12,
        'rev': 8,
        'var': 2,
        'insa': 2,
        'insb': 2,
        'adins': 2,
        'vcm': None,
        'mas': None,
    },
    'HD PLATE': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 21,
        'rev': 9,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': None,
        'mas': None,
    },
    'R3 PLATE': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 20,
        'rev': 10,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': None,
        'mas': None,
    },
    'SPX STAGE': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 30,
        'rev': 11,
        'var': 3,
        'insa': 3,
        'insb': 3,
        'adins': 3,
        'vcm': None,
        'mas': None,
    },
    'SPACE SIMULATOR': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 40,
        'rev': 12,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': None,
        'mas': None,
    },
    'GATED REVERB': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 50,
        'rev': None,
        'var': 4,
        'insa': 4,
        'insb': 4,
        'adins': 4,
        'vcm': None,
        'mas': None,
    },
    'REVERSE REVERB': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 58,
        'rev': None,
        'var': 5,
        'insa': 5,
        'insb': 5,
        'adins': 5,
        'vcm': None,
        'mas': None,
    },
    'SHIMMER REVERB': {
        'category': 'REVERB',
        'short_name': 'REV',
        'msb': 1,
        'lsb': 60,
        'rev': 13,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': None,
        'mas': None,
    },
    'CROSS DELAY': {
        'category': 'DELAY',
        'short_name': 'DLY',
        'msb': 2,
        'lsb': 0,
        'rev': None,
        'var': 6,
        'insa': 6,
        'insb': 6,
        'adins': 6,
        'vcm': None,
        'mas': None,
    },
    'TEMPO CROSS DELAY': {
        'category': 'DELAY',
        'short_name': 'DLY',
        'msb': 2,
        'lsb': 10,
        'rev': None,
        'var': 7,
        'insa': 7,
        'insb': 7,
        'adins': 7,
        'vcm': None,
        'mas': None,
    },
    'TEMPO DELAY MONO': {
        'category': 'DELAY',
        'short_name': 'DLY',
        'msb': 2,
        'lsb': 20,
        'rev': None,
        'var': 8,
        'insa': 8,
        'insb': 8,
        'adins': 8,
        'vcm': None,
        'mas': None,
    },
    'TEMPO DELAY STEREO': {
        'category': 'DELAY',
        'short_name': 'DLY',
        'msb': 2,
        'lsb': 28,
        'rev': None,
        'var': 9,
        'insa': 9,
        'insb': 9,
        'adins': 9,
        'vcm': None,
        'mas': None,
    },
    'CONTROL DELAY': {
        'category': 'DELAY',
        'short_name': 'DLY',
        'msb': 2,
        'lsb': 30,
        'rev': None,
        'var': 10,
        'insa': 10,
        'insb': 10,
        'adins': 10,
        'vcm': None,
        'mas': None,
    },
    'DELAY LR': {
        'category': 'DELAY',
        'short_name': 'DLY',
        'msb': 2,
        'lsb': 40,
        'rev': None,
        'var': 11,
        'insa': 11,
        'insb': 11,
        'adins': 11,
        'vcm': None,
        'mas': 0,
    },
    'DELAY LCR': {
        'category': 'DELAY',
        'short_name': 'DLY',
        'msb': 2,
        'lsb': 50,
        'rev': None,
        'var': 12,
        'insa': 12,
        'insb': 12,
        'adins': 12,
        'vcm': None,
        'mas': None,
    },
    'ANALOG DELAY RETRO': {
        'category': 'DELAY',
        'short_name': 'DLY',
        'msb': 2,
        'lsb': 60,
        'rev': None,
        'var': 13,
        'insa': 13,
        'insb': 13,
        'adins': 13,
        'vcm': None,
        'mas': None,
    },
    'ANALOG DELAY MODERN': {
        'category': 'DELAY',
        'short_name': 'DLY',
        'msb': 2,
        'lsb': 68,
        'rev': None,
        'var': 14,
        'insa': 14,
        'insb': 14,
        'adins': 14,
        'vcm': None,
        'mas': None,
    },
    'G CHORUS': {
        'category': 'CHORUS',
        'short_name': 'CHO',
        'msb': 3,
        'lsb': 0,
        'rev': None,
        'var': 15,
        'insa': 15,
        'insb': 15,
        'adins': 15,
        'vcm': None,
        'mas': None,
    },
    '2 MODULATOR': {
        'category': 'CHORUS',
        'short_name': 'CHO',
        'msb': 3,
        'lsb': 10,
        'rev': None,
        'var': 16,
        'insa': 16,
        'insb': 16,
        'adins': 16,
        'vcm': None,
        'mas': None,
    },
    'SPX CHORUS': {
        'category': 'CHORUS',
        'short_name': 'CHO',
        'msb': 3,
        'lsb': 20,
        'rev': None,
        'var': 17,
        'insa': 17,
        'insb': 17,
        'adins': 17,
        'vcm': None,
        'mas': None,
    },
    'SYMPHONIC': {
        'category': 'CHORUS',
        'short_name': 'CHO',
        'msb': 3,
        'lsb': 30,
        'rev': None,
        'var': 18,
        'insa': 18,
        'insb': 18,
        'adins': 18,
        'vcm': None,
        'mas': None,
    },
    'ENSEMBLE DETUNE': {
        'category': 'CHORUS',
        'short_name': 'CHO',
        'msb': 3,
        'lsb': 40,
        'rev': None,
        'var': 19,
        'insa': 19,
        'insb': 19,
        'adins': 19,
        'vcm': None,
        'mas': None,
    },
    'VCM FLANGER': {
        'category': 'FLANGER',
        'short_name': 'FLG',
        'msb': 4,
        'lsb': 0,
        'rev': None,
        'var': 20,
        'insa': 20,
        'insb': 20,
        'adins': 20,
        'vcm': None,
        'mas': None,
    },
    'CLASSIC FLANGER': {
        'category': 'FLANGER',
        'short_name': 'FLG',
        'msb': 4,
        'lsb': 10,
        'rev': None,
        'var': 21,
        'insa': 21,
        'insb': 21,
        'adins': 21,
        'vcm': None,
        'mas': None,
    },
    'TEMPO FLANGER': {
        'category': 'FLANGER',
        'short_name': 'FLG',
        'msb': 4,
        'lsb': 20,
        'rev': None,
        'var': 22,
        'insa': 22,
        'insb': 22,
        'adins': 22,
        'vcm': None,
        'mas': None,
    },
    'DYNAMIC FLANGER': {
        'category': 'FLANGER',
        'short_name': 'FLG',
        'msb': 4,
        'lsb': 30,
        'rev': None,
        'var': 23,
        'insa': 23,
        'insb': 23,
        'adins': 23,
        'vcm': None,
        'mas': None,
    },
    'CONTROL FLANGER': {
        'category': 'FLANGER',
        'short_name': 'FLG',
        'msb': 4,
        'lsb': 8,
        'rev': None,
        'var': 24,
        'insa': 24,
        'insb': 24,
        'adins': 24,
        'vcm': None,
        'mas': None,
    },
    'VCM PHASER MONO': {
        'category': 'PHASER',
        'short_name': 'PHA',
        'msb': 5,
        'lsb': 0,
        'rev': None,
        'var': 25,
        'insa': 25,
        'insb': 25,
        'adins': 25,
        'vcm': None,
        'mas': None,
    },
    'VCM PHASER STEREO': {
        'category': 'PHASER',
        'short_name': 'PHA',
        'msb': 5,
        'lsb': 10,
        'rev': None,
        'var': 26,
        'insa': 26,
        'insb': 26,
        'adins': 26,
        'vcm': None,
        'mas': None,
    },
    'TEMPO PHASER': {
        'category': 'PHASER',
        'short_name': 'PHA',
        'msb': 5,
        'lsb': 20,
        'rev': None,
        'var': 27,
        'insa': 27,
        'insb': 27,
        'adins': 27,
        'vcm': None,
        'mas': None,
    },
    'DYNAMIC PHASER': {
        'category': 'PHASER',
        'short_name': 'PHA',
        'msb': 5,
        'lsb': 30,
        'rev': None,
        'var': 28,
        'insa': 28,
        'insb': 28,
        'adins': 28,
        'vcm': None,
        'mas': None,
    },
    'CONTROL PHASER': {
        'category': 'PHASER',
        'short_name': 'PHA',
        'msb': 5,
        'lsb': 18,
        'rev': None,
        'var': 29,
        'insa': 29,
        'insb': 29,
        'adins': 29,
        'vcm': None,
        'mas': None,
    },
    'AUTO PAN': {
        'category': 'TREMOLO&ROTARY',
        'short_name': 'T&R',
        'msb': 6,
        'lsb': 0,
        'rev': None,
        'var': 30,
        'insa': 30,
        'insb': 30,
        'adins': 30,
        'vcm': None,
        'mas': None,
    },
    'TREMOLO': {
        'category': 'TREMOLO&ROTARY',
        'short_name': 'T&R',
        'msb': 6,
        'lsb': 10,
        'rev': None,
        'var': 31,
        'insa': 31,
        'insb': 31,
        'adins': 31,
        'vcm': None,
        'mas': None,
    },
    'ROTARY SPEAKER 1': {
        'category': 'TREMOLO&ROTARY',
        'short_name': 'T&R',
        'msb': 6,
        'lsb': 20,
        'rev': None,
        'var': 32,
        'insa': 32,
        'insb': 32,
        'adins': 32,
        'vcm': None,
        'mas': None,
    },
    'ROTARY SPEAKER 2': {
        'category': 'TREMOLO&ROTARY',
        'short_name': 'T&R',
        'msb': 6,
        'lsb': 30,
        'rev': None,
        'var': 33,
        'insa': 33,
        'insb': 33,
        'adins': 33,
        'vcm': None,
        'mas': None,
    },
    'VCM ROTARY SPEAKER CLASSIC': {
        'category': 'TREMOLO&ROTARY',
        'short_name': 'T&R',
        'msb': 6,
        'lsb': 40,
        'rev': None,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': 0,
        'mas': None,
    },
    'VCM ROTARY SPEAKER OVERDRIVE': {
        'category': 'TREMOLO&ROTARY',
        'short_name': 'T&R',
        'msb': 6,
        'lsb': 41,
        'rev': None,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': 1,
        'mas': None,
    },
    'VCM ROTARY SPEAKER STUDIO': {
        'category': 'TREMOLO&ROTARY',
        'short_name': 'T&R',
        'msb': 6,
        'lsb': 42,
        'rev': None,
        'var': None,
        'insa': None,
        'insb': None,
        'adins': None,
        'vcm': 2,
        'mas': None,
    },
    'AMP SIMULATOR 1': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 0,
        'rev': None,
        'var': 34,
        'insa': 34,
        'insb': 34,
        'adins': 34,
        'vcm': None,
        'mas': None,
    },
    'AMP SIMULATOR 2': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 10,
        'rev': None,
        'var': 35,
        'insa': 35,
        'insb': 35,
        'adins': 35,
        'vcm': None,
        'mas': None,
    },
    'COMP DISTORTION': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 20,
        'rev': None,
        'var': 36,
        'insa': 36,
        'insb': 36,
        'adins': 36,
        'vcm': None,
        'mas': None,
    },
    'COMP DISTORTION DELAY': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 30,
        'rev': None,
        'var': 37,
        'insa': 37,
        'insb': 37,
        'adins': 37,
        'vcm': None,
        'mas': 1,
    },
    'US COMBO': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 40,
        'rev': None,
        'var': 38,
        'insa': 38,
        'insb': 38,
        'adins': 38,
        'vcm': None,
        'mas': None,
    },
    'JAZZ COMBO': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 41,
        'rev': None,
        'var': 39,
        'insa': 39,
        'insb': 39,
        'adins': 39,
        'vcm': None,
        'mas': None,
    },
    'US HIGH GAIN': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 42,
        'rev': None,
        'var': 40,
        'insa': 40,
        'insb': 40,
        'adins': 40,
        'vcm': None,
        'mas': None,
    },
    'BRITISH LEAD': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 43,
        'rev': None,
        'var': 41,
        'insa': 41,
        'insb': 41,
        'adins': 41,
        'vcm': None,
        'mas': None,
    },
    'MULTI FX': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 44,
        'rev': None,
        'var': 42,
        'insa': 42,
        'insb': 42,
        'adins': 42,
        'vcm': None,
        'mas': None,
    },
    'SMALL STEREO': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 45,
        'rev': None,
        'var': 43,
        'insa': 43,
        'insb': 43,
        'adins': 43,
        'vcm': None,
        'mas': None,
    },
    'BRITISH COMBO': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 46,
        'rev': None,
        'var': 44,
        'insa': 44,
        'insb': 44,
        'adins': 44,
        'vcm': None,
        'mas': None,
    },
    'BRITISH LEGEND': {
        'category': 'DISTORTION',
        'short_name': 'DST',
        'msb': 7,
        'lsb': 47,
        'rev': None,
        'var': 45,
        'insa': 45,
        'insb': 45,
        'adins': 45,
        'vcm': None,
        'mas': None,
    },
    'VCM COMPRESSOR 376': {
        'category': 'COMPRESSOR',
        'short_name': 'CMP',
        'msb': 8,
        'lsb': 0,
        'rev': None,
        'var': 46,
        'insa': 46,
        'insb': 46,
        'adins': 46,
        'vcm': None,
        'mas': 2,
    },
    'CLASSIC COMPRESSOR': {
        'category': 'COMPRESSOR',
        'short_name': 'CMP',
        'msb': 8,
        'lsb': 10,
        'rev': None,
        'var': 47,
        'insa': 47,
        'insb': 47,
        'adins': 47,
        'vcm': None,
        'mas': None,
    },
    'MULTI BAND COMP': {
        'category': 'COMPRESSOR',
        'short_name': 'CMP',
        'msb': 8,
        'lsb': 20,
        'rev': None,
        'var': 48,
        'insa': 48,
        'insb': 48,
        'adins': 48,
        'vcm': None,
        'mas': 3,
    },
    'UNI COMP DOWN': {
        'category': 'COMPRESSOR',
        'short_name': 'CMP',
        'msb': 8,
        'lsb': 30,
        'rev': None,
        'var': 49,
        'insa': 49,
        'insb': 49,
        'adins': 49,
        'vcm': None,
        'mas': 4,
    },
    'UNI COMP UP': {
        'category': 'COMPRESSOR',
        'short_name': 'CMP',
        'msb': 8,
        'lsb': 38,
        'rev': None,
        'var': 50,
        'insa': 50,
        'insb': 50,
        'adins': 50,
        'vcm': None,
        'mas': 5,
    },
    'PARALLEL COMP': {
        'category': 'COMPRESSOR',
        'short_name': 'CMP',
        'msb': 8,
        'lsb': 40,
        'rev': None,
        'var': 51,
        'insa': 51,
        'insb': 51,
        'adins': 51,
        'vcm': None,
        'mas': 6,
    },
    'VCM AUTO WAH': {
        'category': 'WAH',
        'short_name': 'WAH',
        'msb': 10,
        'lsb': 0,
        'rev': None,
        'var': 52,
        'insa': 52,
        'insb': 52,
        'adins': 52,
        'vcm': None,
        'mas': None,
    },
    'VCM TOUCH WAH': {
        'category': 'WAH',
        'short_name': 'WAH',
        'msb': 10,
        'lsb': 10,
        'rev': None,
        'var': 53,
        'insa': 53,
        'insb': 53,
        'adins': 53,
        'vcm': None,
        'mas': None,
    },
    'VCM PEDAL WAH': {
        'category': 'WAH',
        'short_name': 'WAH',
        'msb': 10,
        'lsb': 20,
        'rev': None,
        'var': 54,
        'insa': 54,
        'insb': 54,
        'adins': 54,
        'vcm': None,
        'mas': None,
    },
    'LO-FI': {
        'category': 'LO-FI',
        'short_name': 'L-F',
        'msb': 11,
        'lsb': 0,
        'rev': None,
        'var': 55,
        'insa': 55,
        'insb': 55,
        'adins': 55,
        'vcm': None,
        'mas': 7,
    },
    'NOISY': {
        'category': 'LO-FI',
        'short_name': 'L-F',
        'msb': 11,
        'lsb': 10,
        'rev': None,
        'var': 56,
        'insa': 56,
        'insb': 56,
        'adins': 56,
        'vcm': None,
        'mas': None,
    },
    'DIGITAL TURNTABLE': {
        'category': 'LO-FI',
        'short_name': 'L-F',
        'msb': 11,
        'lsb': 20,
        'rev': None,
        'var': 57,
        'insa': 57,
        'insb': 57,
        'adins': 57,
        'vcm': None,
        'mas': None,
    },
    'BIT CRUSHER': {
        'category': 'LO-FI',
        'short_name': 'L-F',
        'msb': 11,
        'lsb': 30,
        'rev': None,
        'var': 58,
        'insa': 58,
        'insb': 58,
        'adins': 58,
        'vcm': None,
        'mas': 8,
    },
    'RING MODULATOR': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 0,
        'rev': None,
        'var': 59,
        'insa': 59,
        'insb': 59,
        'adins': 59,
        'vcm': None,
        'mas': 9,
    },
    'DYNAMIC RING MODULATOR': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 10,
        'rev': None,
        'var': 60,
        'insa': 60,
        'insb': 60,
        'adins': 60,
        'vcm': None,
        'mas': None,
    },
    'DYNAMIC FILTER': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 20,
        'rev': None,
        'var': 61,
        'insa': 61,
        'insb': 61,
        'adins': 61,
        'vcm': None,
        'mas': 10,
    },
    'AUTO SYNTH': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 30,
        'rev': None,
        'var': 62,
        'insa': 62,
        'insb': 62,
        'adins': 62,
        'vcm': None,
        'mas': None,
    },
    'SPIRALIZER P': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 38,
        'rev': None,
        'var': 63,
        'insa': 63,
        'insb': 63,
        'adins': 63,
        'vcm': None,
        'mas': 11,
    },
    'TEMPO SPIRALIZER P': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 39,
        'rev': None,
        'var': 64,
        'insa': 64,
        'insb': 64,
        'adins': 64,
        'vcm': None,
        'mas': 12,
    },
    'SPIRALIZER F': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 58,
        'rev': None,
        'var': 65,
        'insa': 65,
        'insb': 65,
        'adins': 65,
        'vcm': None,
        'mas': 13,
    },
    'TEMPO SPIRALIZER F': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 59,
        'rev': None,
        'var': 66,
        'insa': 66,
        'insb': 66,
        'adins': 66,
        'vcm': None,
        'mas': 14,
    },
    'ISOLATOR': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 40,
        'rev': None,
        'var': 67,
        'insa': 67,
        'insb': 67,
        'adins': 67,
        'vcm': None,
        'mas': 15,
    },
    'SLICE': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 50,
        'rev': None,
        'var': 68,
        'insa': 68,
        'insb': 68,
        'adins': 68,
        'vcm': None,
        'mas': 16,
    },
    'TECH MODULATION': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 60,
        'rev': None,
        'var': 69,
        'insa': 69,
        'insb': 69,
        'adins': 69,
        'vcm': None,
        'mas': None,
    },
    'CONTROL FILTER': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 28,
        'rev': None,
        'var': 70,
        'insa': 70,
        'insb': 70,
        'adins': 70,
        'vcm': None,
        'mas': None,
    },
    'VINYL BREAK': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 70,
        'rev': None,
        'var': 71,
        'insa': 71,
        'insb': 71,
        'adins': None,
        'vcm': None,
        'mas': 17,
    },
    'BEAT REPEAT EVEN': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 78,
        'rev': None,
        'var': 72,
        'insa': 72,
        'insb': 72,
        'adins': None,
        'vcm': None,
        'mas': 18,
    },
    'BEAT REPEAT TRIPLET': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 79,
        'rev': None,
        'var': 73,
        'insa': 73,
        'insb': 73,
        'adins': None,
        'vcm': None,
        'mas': 19,
    },
    'BEAT REPEAT EVEN+TRIPLET': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 122,
        'rev': None,
        'var': 74,
        'insa': 74,
        'insb': 74,
        'adins': None,
        'vcm': None,
        'mas': 20,
    },
    'BEAT REPEAT FREE': {
        'category': 'TECH',
        'short_name': 'TEC',
        'msb': 12,
        'lsb': 123,
        'rev': None,
        'var': 75,
        'insa': 75,
        'insb': 75,
        'adins': None,
        'vcm': None,
        'mas': 21,
    },
    'VCM EQ 501': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 0,
        'rev': None,
        'var': 76,
        'insa': 76,
        'insb': 76,
        'adins': 71,
        'vcm': None,
        'mas': None,
    },
    'PRESENCE': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 8,
        'rev': None,
        'var': 77,
        'insa': 77,
        'insb': 77,
        'adins': 72,
        'vcm': None,
        'mas': 22,
    },
    'HARMONIC ENHANCER': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 10,
        'rev': None,
        'var': 78,
        'insa': 78,
        'insb': 78,
        'adins': 73,
        'vcm': None,
        'mas': None,
    },
    'STEREOPHONIC OPTIMIZER': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 18,
        'rev': None,
        'var': 79,
        'insa': 79,
        'insb': 79,
        'adins': 74,
        'vcm': None,
        'mas': None,
    },
    'TALKING MODULATOR': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 20,
        'rev': None,
        'var': 80,
        'insa': 80,
        'insb': 80,
        'adins': 75,
        'vcm': None,
        'mas': None,
    },
    'WAVE FOLDER': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 28,
        'rev': None,
        'var': 81,
        'insa': 81,
        'insb': 81,
        'adins': 76,
        'vcm': None,
        'mas': 23,
    },
    'VCM MINI FILTER': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 29,
        'rev': None,
        'var': 82,
        'insa': 82,
        'insb': 82,
        'adins': 77,
        'vcm': None,
        'mas': 24,
    },
    'VCM MINI BOOSTER': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 42,
        'rev': None,
        'var': 83,
        'insa': 83,
        'insb': 83,
        'adins': 78,
        'vcm': None,
        'mas': 25,
    },
    'DAMPER RESONANCE': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 30,
        'rev': None,
        'var': 84,
        'insa': 84,
        'insb': 84,
        'adins': 79,
        'vcm': None,
        'mas': None,
    },
    'PITCH CHANGE': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 40,
        'rev': None,
        'var': 85,
        'insa': 85,
        'insb': 85,
        'adins': 80,
        'vcm': None,
        'mas': None,
    },
    'EARLY REFLECTION': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 50,
        'rev': None,
        'var': 86,
        'insa': 86,
        'insb': 86,
        'adins': 81,
        'vcm': None,
        'mas': None,
    },
    'VOCODER': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 60,
        'rev': None,
        'var': 87,
        'insa': 87,
        'insb': 87,
        'adins': 82,
        'vcm': None,
        'mas': None,
    },
    'NOISE GATE+COMP+EQ': {
        'category': 'MISC',
        'short_name': 'MSC',
        'msb': 13,
        'lsb': 70,
        'rev': None,
        'var': 88,
        'insa': 88,
        'insb': 88,
        'adins': 83,
        'vcm': None,
        'mas': None,
    },
}


# Type-index = msb * 128 + lsb (binärkodning i Y2L-fil)
def fx_type_index(name):
    """Get binary type-index for an FX name."""
    fx = FX_TYPES.get(name)
    if fx is None: return 0
    return fx['msb'] * 128 + fx['lsb']

def fx_type_bytes(name):
    """Returns (lo, hi) byte tuple för Y2L-encoding."""
    fx = FX_TYPES.get(name)
    if fx is None: return (0, 0)
    return (fx['lsb'], fx['msb'])

def fx_name_from_bytes(lo, hi):
    """Reverse lookup: get FX name from (lo, hi) bytes."""
    for name, fx in FX_TYPES.items():
        if fx['msb'] == hi and fx['lsb'] == lo:
            return name
    return f'UNKNOWN(lo={lo}, hi={hi})'

# Reverse lookup tables för snabb access
FX_TYPE_INDEX = {name: fx_type_index(name) for name in FX_TYPES}
FX_INDEX_TO_NAME = {idx: name for name, idx in FX_TYPE_INDEX.items()}


# Filtrera per slot — ger lista av tillgängliga effekter för varje slot
def fx_for_slot(slot):
    """Returns sorted list of (slot_index, name) for given slot.
    slot: 'rev', 'var', 'insa', 'insb', 'adins', 'vcm', 'mas'
    """
    result = []
    for name, fx in FX_TYPES.items():
        idx = fx.get(slot)
        if idx is not None:
            result.append((idx, name))
    return sorted(result, key=lambda x: x[0])

# Pre-computed lists för UI-dropdowns
FX_REV_LIST = fx_for_slot('rev')      # Reverb-slot
FX_VAR_LIST = fx_for_slot('var')      # Variation-slot
FX_INSA_LIST = fx_for_slot('insa')    # Insertion A
FX_INSB_LIST = fx_for_slot('insb')    # Insertion B
FX_ADINS_LIST = fx_for_slot('adins')  # Audio In Insertion
FX_MAS_LIST = fx_for_slot('mas')      # Master FX
FX_VCM_LIST = fx_for_slot('vcm')      # VCM Rotary

# Categories
FX_CATEGORIES = sorted(set(fx['category'] for fx in FX_TYPES.values() if fx['category']))


if __name__ == '__main__':
    print(f"Total FX types: {len(FX_TYPES)}")
    for slot in ['rev', 'var', 'insa', 'insb', 'adins', 'mas']:
        items = fx_for_slot(slot)
        print(f"  {slot}-slot: {len(items)} effects")
